spring.application.name=acknobit
server.port=8080

# Spring AI Google GenAI Setup
spring.ai.openai.api-key=YOUR_API_KEY

spring.ai.openai.base-url=YOUR_OPENAI_URL
spring.ai.openai.chat.options.model=YOUR_MODEL