spring.application.name=acknobit
server.port=8080

# Spring AI Google GenAI Setup
spring.ai.openai.api-key=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

spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile